language: node_js
node_js:
  - 10
before_script:
  - npm install firebase-tools -g
  - npm install @11ty/eleventy -g
  - npm install
  - npm run build
script:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
